CREATE TABLE
    IF NOT EXISTS items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        img_path VARCHAR(500) NOT NULL,
        price BIGINT NOT NULL
    );

CREATE TABLE
    IF NOT EXISTS orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP NOT NULL,
        total_sum BIGINT NOT NULL
    );

CREATE TABLE
    IF NOT EXISTS order_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT,
        item_id BIGINT NOT NULL,
        count INTEGER NOT NULL,
        price BIGINT NOT NULL,
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
        FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
    );