spring:
  application:
    name: payment-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/bom-bom-market
          jwk-set-uri: http://localhost:8085/realms/bom-bom-market/protocol/openid-connect/certs

server:
  port: 8082

payment:
  service:
    initial-balance: 100000

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    ru.art.home.payment: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics