DROP TABLE IF EXISTS order_items;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS carts;

DROP TABLE IF EXISTS items;

DROP TABLE IF EXISTS authorities;

DROP TABLE IF EXISTS users;

CREATE TABLE
    IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        enabled BOOLEAN DEFAULT TRUE,
        balance BIGINT DEFAULT 100000
    );

CREATE TABLE
    IF NOT EXISTS authorities (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR(255) NOT NULL,
        authority VARCHAR(255) NOT NULL,
        FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE
    );

CREATE TABLE
    IF NOT EXISTS items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        img_path VARCHAR(500) NOT NULL,
        price BIGINT NOT NULL
    );

CREATE TABLE
    IF NOT EXISTS orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        created_at TIMESTAMP NOT NULL,
        total_sum BIGINT NOT NULL,
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE
    IF NOT EXISTS order_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT,
        item_id BIGINT NOT NULL,
        count INTEGER NOT NULL,
        price BIGINT NOT NULL,
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
        FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
    );

CREATE TABLE
    IF NOT EXISTS carts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        item_id BIGINT NOT NULL,
        count INTEGER NOT NULL CHECK (count > 0),
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
        FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
        UNIQUE (user_id, item_id)
    );

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders (user_id);

CREATE INDEX IF NOT EXISTS idx_carts_user_id ON carts (user_id);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);